#!/bin/sh

SYSTEM_ROOT=$1

# Check if root user
if [[ "$USER" == "root" ]]; then
	
	# Check number of arguments
	if [[ "$#" == "1" ]]; then
		
		# Unmount /.snapshots
		umount -lf /.snapshots

		# Remove /.snapshots directory
		rm -rf /.snapshots

		# Run snapper root config
		snapper -c root create-config /

		# Remove /.snapshots directory
		rm -rf /.snapshots

		# Create /.snapshots directory
		mkdir -p /.snapshots

		# Mount @snapshots subvolume back to /.snapshots
		mount -t btrfs -o rw,compress=zstd:6,relatime,commit=120,subvol=@snapshots $SYSTEM_ROOT /.snapshots
	
	else

		# Response message
		echo "Please type in the device name where snapshots will be stored (i.e. /dev/sda2)"

	fi

else

	# Response message
	echo "Please become root before running this script"

fi
