#!/bin/sh
# This script is designed to work with Archlinux

# Get mountpoints
MOUNTPOINT_ROOT=`mount | grep " / " | cut -d " " -f 1`

# Get your disk name and root partition UUID.
INSTALL_DISK=`lsblk -o PKNAME ${MOUNTPOINT_ROOT} | tail -1`
ROOT_UUID=`lsblk -o UUID ${MOUNTPOINT_ROOT} | tail -1`

# Check your cpu and gpu vendor
CPU=`lshw -class cpu | grep "vendor" | cut -d ":" -f 2 | cut -d " " -f 2`
GPU=`lshw -class video | grep "vendor" | cut -d ":" -f 2 | cut -d " " -f 2`

# Commandline Options
EFI_OPTIONS="zswap.enabled=1 zswap.shrinker_enabled=1 zswap.compressor=zstd zswap.max_pool_percent=25 rootfstype=btrfs resume=UUID=${ROOT_UUID} root=UUID=${ROOT_UUID} mitigations=off threadirqs rw rootflags=subvol=@ loglevel=3 nowatchdog"


# Main Program
if [[ "$USER" == "root" ]]; then

	# Entry Creation Wizard
    clear
    echo "EFI boot stub creation wizard"
    echo ""
    ls /boot/vmlinuz* | tr " " "\n" | cut -d "-" -f 2,3
    echo ""
    read -r -p "Choose your kernel entry (i.e. linux, linux-zen): " KERNEL

    # Check if you want nvidia to use the foss or nvidia's open drivers
    if [[ "${GPU}" == "NVIDIA" ]]; then
		read -r -p "Do you want to use the nvidia foss drivers? (Options: yes or no): " NVIDIA_FOSS
    fi

    clear

	# Create EFIStub entries based of CPU choice
	if [[ "${CPU}" == "Advanced" ]]; then

		# AMD EFISTUB entry
		if [[ "${GPU}" == "NVIDIA" ]]; then

			if [[ "${NVIDIA_FOSS}" == "no" ]]; then
				# Install all the needed packages for the proprietary nvidia driver
				pacman -Syy --noconfirm lib32-nvidia-utils lib32-opencl-nvidia libva-nvidia-driver libvdpau-va-gl nvidia-open-dkms nvidia-settings nvidia-utils nvtop opencl-nvidia vdpauinfo
				pacman -Rsc --noconfirm lib32-vulkan-nouveau vulkan-nouveau

				# Create a UEFI entry
				efibootmgr --create --disk /dev/${INSTALL_DISK} --part 1 --label "Arch Linux" --loader /vmlinuz-${KERNEL} --unicode "${EFI_OPTIONS} nvidia-drm.modeset=1 initrd=\amd-ucode.img initrd=\initramfs-${KERNEL}.img"

			elif [[ "${NVIDIA_FOSS}" == "yes" ]]; then
				# Install only the needed packages for the foss nouveau driver
				pacman -Syy --noconfirm lib32-vulkan-nouveau vulkan-nouveau
				pacman -Rsc --noconfirm lib32-nvidia-utils lib32-opencl-nvidia libva-nvidia-driver libvdpau-va-gl nvidia-open-dkms nvidia-settings nvidia-utils nvtop opencl-nvidia vdpauinfo

				# Create a UEFI entry
				efibootmgr --create --disk /dev/${INSTALL_DISK} --part 1 --label "Arch Linux" --loader /vmlinuz-${KERNEL} --unicode "${EFI_OPTIONS} nouveau.config=NvGspRm=1 initrd=\amd-ucode.img initrd=\initramfs-${KERNEL}.img"
			fi

		else
			# Create a UEFI entry
			efibootmgr --create --disk /dev/${INSTALL_DISK} --part 1 --label "Arch Linux" --loader /vmlinuz-${KERNEL} --unicode "${EFI_OPTIONS} initrd=\amd-ucode.img initrd=\initramfs-${KERNEL}.img"
		fi

	elif [[ "${CPU}" == "Intel" ]]; then

		# Intel EFISTUB entry
		if [[ "${GPU}" == "NVIDIA" ]]; then

			if [[ "${NVIDIA_FOSS}" == "no" ]]; then
				# Install all the needed packages for the proprietary nvidia driver
				pacman -Syy --noconfirm lib32-nvidia-utils lib32-opencl-nvidia libva-nvidia-driver libvdpau-va-gl nvidia-open-dkms nvidia-settings nvidia-utils nvtop opencl-nvidia vdpauinfo
				pacman -Rsc --noconfirm lib32-vulkan-nouveau vulkan-nouveau

				# Create a UEFI entry
				efibootmgr --create --disk /dev/${INSTALL_DISK} --part 1 --label "Arch Linux" --loader /vmlinuz-${KERNEL} --unicode "${EFI_OPTIONS} nvidia-drm.modeset=1 initrd=\intel-ucode.img initrd=\initramfs-${KERNEL}.img"

			elif [[ "${NVIDIA_FOSS}" == "yes" ]]; then
				# Install only the needed packages for the foss nouveau driver
				pacman -Syy --noconfirm lib32-vulkan-nouveau vulkan-nouveau
				pacman -Rsc --noconfirm lib32-nvidia-utils lib32-opencl-nvidia libva-nvidia-driver libvdpau-va-gl nvidia-open-dkms nvidia-settings nvidia-utils nvtop opencl-nvidia vdpauinfo

				# Create a UEFI entry
				efibootmgr --create --disk /dev/${INSTALL_DISK} --part 1 --label "Arch Linux" --loader /vmlinuz-${KERNEL} --unicode "${EFI_OPTIONS} nouveau.config=NvGspRm=1 initrd=\intel-ucode.img initrd=\initramfs-${KERNEL}.img"
			fi

		else
			# Create a UEFI entry
			efibootmgr --create --disk /dev/${INSTALL_DISK} --part 1 --label "Arch Linux" --loader /vmlinuz-${KERNEL} --unicode "${EFI_OPTIONS} initrd=\intel-ucode.img initrd=\initramfs-${KERNEL}.img"
		fi

	else

		# EFISTUB entry no microcode
		if [[ "${GPU}" == "NVIDIA" ]]; then

			if [[ "${NVIDIA_FOSS}" == "no" ]]; then
				# Install all the needed packages for the proprietary nvidia driver
				pacman -Syy --noconfirm lib32-nvidia-utils lib32-opencl-nvidia libva-nvidia-driver libvdpau-va-gl nvidia-open-dkms nvidia-settings nvidia-utils nvtop opencl-nvidia vdpauinfo
				pacman -Rsc --noconfirm lib32-vulkan-nouveau vulkan-nouveau

				# Create a UEFI entry
				efibootmgr --create --disk /dev/${INSTALL_DISK} --part 1 --label "Arch Linux" --loader /vmlinuz-${KERNEL} --unicode "${EFI_OPTIONS} nvidia-drm.modeset=1 initrd=\initramfs-${KERNEL}.img"

			elif [[ "${NVIDIA_FOSS}" == "yes" ]]; then
				# Install only the needed packages for the foss nouveau driver
				pacman -Syy --noconfirm lib32-vulkan-nouveau vulkan-nouveau
				pacman -Rsc --noconfirm lib32-nvidia-utils lib32-opencl-nvidia libva-nvidia-driver libvdpau-va-gl nvidia-open-dkms nvidia-settings nvidia-utils nvtop opencl-nvidia vdpauinfo

				# Create a UEFI entry
				efibootmgr --create --disk /dev/${INSTALL_DISK} --part 1 --label "Arch Linux" --loader /vmlinuz-${KERNEL} --unicode "${EFI_OPTIONS} nouveau.config=NvGspRm=1 initrd=\initramfs-${KERNEL}.img"
			fi

		else
			# Create a UEFI entry
			efibootmgr --create --disk /dev/${INSTALL_DISK} --part 1 --label "Arch Linux" --loader /vmlinuz-${KERNEL} --unicode "${EFI_OPTIONS} initrd=\initramfs-${KERNEL}.img"
		fi

	fi

	# Return to terminal
    clear
    fastfetch
    echo ""

else

    # Message when not root
    echo "Please become root before running this script..."

fi
